@baseUrl = https://localhost:7007/identity

### Login As Manager
POST {{baseUrl}}/token/generate
Content-Type: application/json

{
    "email": "pm@localhost",
    "password": "pm@localhost"
}

### Login As Labor
POST {{baseUrl}}/token/generate
Content-Type: application/json

{
    "email": "john.labor@localhost",
    "password": "john.labor@localhost"
}

### Refresh Token
POST {{baseUrl}}/token/refresh-token
Content-Type: application/json

{
    "ExpiredAccessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxOWE1OTEyOS02YzIwLTQxN2EtODM0ZC0xMWEyMDhkMzJkOTYiLCJlbWFpbCI6InBtQGxvY2FsaG9zdCIsInJvbGUiOiJNYW5hZ2VyIiwibmJmIjoxNzU2MzE0NDY4LCJleHAiOjE3NTYzMTgwNjgsImlhdCI6MTc1NjMxNDQ2OCwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.XM-0IwgKENtALhngLZQemJVDKA3zXDU2YKl2ZTIuLms",
    "refreshToken": "UHgAl0SIFatuBsd6YImmW+4ibk8cVT99/sfNmtQQNH0="
}
